Improve lookup table creation and type inference #1235
Felienne/hedy pull request #1236
Opened 2021-11-11 14:31 UTC by boryanagoncharenko

**Description**

- separate lookup table creation in 2:
  in the first pass we only keep the name of the entry and the Tree object of its value
  in the second pass we infer the type of the lookup entry

- changed list access index to be 1-based since level 2

- refactor hedy.transpile_inner method

- fixed a translation error in the adventures/el.yaml causing a flaky test

**Fix for**

#1235 

**How to test**

- All changes should be fully backwards compatible, so ALL tests must pass.

2021-11-11 14:49 UTC, Felienne commented on hedy.py
> +    def forward(self, args):
Love these tiny styling fixes!! ❤️

2021-11-11 15:21 UTC, Felienne requested changes
Only tiny changes in the test, the rest looks amazing to me!

2021-11-11 15:23 UTC, Felienne commented on hedy.py
> +    def add_to_lookup(self, name, tree, skip_hashing=False):
love the extra argument to indicate hashing, a lot less error-prone and more clear this way

2021-11-11 15:23 UTC, Felienne requested changes
One more remark, need to make a separate review it seems

2021-11-11 15:34 UTC, boryanagoncharenko commented on grammars/level2-Additions.lark
> +index : INT //todo FH-June 21 : why does this need its own rule? can't it just be a token
I will try removing the index rule and see what happens when it is just a token

2021-11-11 16:20 UTC, Felienne commented on grammars/level2-Additions.lark
> +index : INT //todo FH-June 21 : why does this need its own rule? can't it just be a token
thanks for looking into this! feel a bit bad about leaving crap like that in the code base now, sorry!

2021-11-11 16:29 UTC, boryanagoncharenko commented on tests/test_level_11.py
> +  def test_print_multiple_calcs(self):
thanks for pointing it out! I revised all tests in level 11.

2021-11-11 16:30 UTC, boryanagoncharenko commented on grammars/level2-Additions.lark
> +index : INT //todo FH-June 21 : why does this need its own rule? can't it just be a token
It seems that no tests are broken when there is no separate index rule. So it is gone now :)

2021-11-12 06:54 UTC, Felienne approved these changes

2021-11-12 06:56 UTC, merged