Update of the whats next adventure NL EN
Felienne/hedy pull request #1557
Opened 2021-12-16 12:44 UTC by MarleenGilsing

all examples work correctly now and every level has a what's next adventure in NL and EN

Provide a general summary of your changes in the Title of the PR

**Description**

Describe your changes in detail. Please use present tense without a subject to describe your PR, for example: "Fix**es** issue 123" or "Adds translations of levels 1 to 12 for Polish"

**Fix for**

Describe what issue or discussion your pr concerns

**How to test**

Describe how to run your code to see it is action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example.

**Checklist**

If you're unsure about any of these, don't hesitate to ask. We're here to help!
- [ ] Links to an existing issue or discussion (if not, create an issue first)
- [ ] Describes changes clear in the format above (present tense, no subject)
- [ ] Has a "how to test" section
- [ ] Only one thing is done in this pull request (specifically please try to refrain from mixing textual changes to the yamls from code changes)

2021-12-17 14:10 UTC, Felienne submitted a review, later dismissed

2021-12-17 14:18 UTC, Felienne approved these changes

2021-12-27 20:01 UTC, StephanEggermont commented
Line 2137                     answer = ask 'Would you like to go to teh next level?'
the -> the

2022-01-05 10:06 UTC, Felienne requested changes

2022-01-05 10:06 UTC, Felienne commented on coursedata/adventures/en.yaml
> +                    But you couldn't use the `if` command, like the code below. This program does not work yet in this level!
Ha @MarleenGilsing!

Dit is niet meer waar want je mag nu in alle levels ook spaties in de if gebruiken, dat hebben we gefikst. Dus deze tekst moet een beetje anders.

2022-01-14 13:40 UTC, Felienne commented
Ha Marleen!

Deze tekst loopt nog niet helemaal 100% lekker want eerst gata het over kommagetallen en dan over aanhalingstekens:

![image](https://user-images.githubusercontent.com/1003685/149524303-507e971b-2cc7-4990-bb6e-5bda496d99c1.png)

Een groter probleem (waarom je een error krijgt) is dat de code in het voorbeeld niet werkt op dit niveau maar ik ga dat even aanpassen in de code want het is eigenlijk wel handig als dat wel mag.

2022-01-14 13:47 UTC, Felienne requested changes
Zie opm hierboven

2022-01-20 08:26 UTC, MarleenGilsing commented
Hoi Felienne, 

Je hebt gelijk! Ik had per ongeluk een zinnetje uit de uitleg verwijderd. Het klopt nu weer. 
Moet ik dat voorbeeld dat niet werkt er nog uithalen? Of werkt dat nu wel?

2022-01-20 19:12 UTC, Felienne commented
> Hoi Felienne,
> 
> Je hebt gelijk! Ik had per ongeluk een zinnetje uit de uitleg verwijderd. Het klopt nu weer. Moet ik dat voorbeeld dat niet werkt er nog uithalen? Of werkt dat nu wel?

Dat werkt nu wel (want als het niet werkte, hadden we hier een fout gekregen) dus alles in orde zo!

2022-01-20 19:22 UTC, Felienne approved these changes

2022-01-20 19:22 UTC, merged