Lock & Unlock
Felienne/hedy pull request #2095
Opened 2022-02-24 17:15 UTC by HanshaLeng

**Please fill out this template by replacing all content between < >**

< Provide a one line summary of your changes in the Title of the PR >

**Description**

< Changes in detail > Use present tense without a subject to describe your PR, for example: "Adds translations of levels 1 to 12 to Polish"

**Fixes < issue or discussion number >**

< Always link the number of the issue or of the discussion that your pr concerns. >
Notable exception: adding content may be done without an accompanying issue 

**How to test**

< If this is a UI change, describe how to run your code to see it in action. See this https://github.com/Felienne/hedy/pull/880#issue-1016304308 for an example >
< If this is a language change, add a few tests showing the difference >

**Checklist**
Done? Check if you have it all in place using this list*
  
- [ ] Describes changes in the format above (present tense)
- [ ] Links to an existing issue or discussion 
- [ ] Has a "How to test" section

* If you're unsure about any of these, don't hesitate to ask. We're here to help!

2022-02-24 18:46 UTC, Felienne commented
I added the generated css but it does not entirely look right, can you look into that:

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/1003685/155587717-483da68d-fde7-41eb-a46b-0dc3cc020436.png">

Otherwise the merge seems ok so you can start testing this version and mix the error up to date with our main.

2022-02-24 18:47 UTC, Felienne commented
There is a code error too but that is probably something small:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/1003685/155587808-e2c3c2cb-0561-46a2-a52f-3e473391de5a.png">

2022-02-25 01:58 UTC, HanshaLeng commented
> There is a code error too but that is probably something small:
> 
> <img alt="image" width="728" src="https://user-images.githubusercontent.com/1003685/155587808-e2c3c2cb-0561-46a2-a52f-3e473391de5a.png">

It seems your merge  added a redundant piece of code from an older version, it cause the fault

2022-03-03 11:42 UTC, TiBiBa requested changes

2022-03-11 14:39 UTC, closed without merging