Quiz UI result overview
Felienne/hedy pull request #2181
Opened 2022-03-07 16:01 UTC by LterHaar

Quiz Result Overview Page

**Description**

Gives an overview of the results of the quiz for each question and visualizes if the question was answered correct and the number of attempts are shown, fixes #977 

**Fixes < issue or discussion number >**

Replaces the original  endquiz results screen.

**How to test**
![End Screen - Achievement](https://user-images.githubusercontent.com/86956321/157070835-21a3b682-82d5-4416-a163-45c8ca15a55f.JPG)
![End screen](https://user-images.githubusercontent.com/86956321/157070971-5096e5d3-ea17-4a2f-8bd8-790fecc84d7b.JPG)

![result screen1](https://user-images.githubusercontent.com/86956321/157070879-f5e2537c-9f62-4f74-a317-ab9a0a0975dd.jpg)

2022-03-07 18:52 UTC, Felienne commented
Thanks @LotusterHaar! Ik zie een paar conflicten maar dit durf ik zelf niet op te lossen. Kan jij er naar kijken? Anders vragen we het @TiBiBa volgende week (hij is nu op vakantie helaas)

2022-03-14 07:46 UTC, Felienne commented
@TiBiBa maybe you can also have a peek at the conflicts here?

2022-03-14 08:03 UTC, TiBiBa submitted a review, later dismissed
Hi @LterHaar! I just left some comments, can you take a look? Just some small questions and requests. I only looked at the code and didn't actually test it (yet). Will do that later today and let you know if I have some questions. Otherwise the code looks great, nice!

2022-03-14 08:03 UTC, TiBiBa commented on templates/quiz-result-overview.html
> +                onclick="window.parent.location = '{{ hedy_link(level, next_assignment) }}';"> {{ ui.go_to_level }} {{ level }} </button>
In this case we do use the `hedy_link` function. Would be nice to do this consistent, either everywhere on not at all.

2022-03-14 08:03 UTC, TiBiBa commented on website/quiz.py
> +        print(result_items)
Can this print be removed before merging?

2022-03-14 08:03 UTC, TiBiBa commented on website/quiz.py
> +    print(questions)
Same for this print

2022-03-14 08:03 UTC, TiBiBa commented on website/quiz.py
> +    for i in range(len(questions)):
Can't we iterate the questions itself instead of using a loop counter. So simply `for question in questions`.

2022-03-14 08:27 UTC, TiBiBa commented
I just fixed the merging errors and it all seems to work fine, awesome! @Felienne I think it would be best to merge this first before #2136 as we do some clean-up to improve the YAML reading structure there. It will be easier to solve the merging conflicts on that PR than the other way around.

2022-03-16 08:23 UTC, Felienne requested changes
Looking good indeed, thanks @LterHaar!

A few tiny things (fine if @TiBiBa picks these up)

The overview looks goed, but it seems we lost syntax highlighting in the quiz? 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1003685/158546960-b23fe742-a06b-43db-bdb4-540f238d0d8e.png">

Also, probably very tiny but the overview (goed, pogingen) is in Duch even though my lang is English:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/1003685/158547045-1259d994-7578-4687-bfea-7f73a9e7ed87.png">

And if we are on the topic of languages anyway, this "Good" is a bit Dunglish, "correct" would be nicer:

<img width="482" alt="image" src="https://user-images.githubusercontent.com/1003685/158547185-d451a203-ed48-4c45-ae0a-4688e2e6d205.png">

2022-03-16 08:24 UTC, TiBiBa commented
> Looking good indeed, thanks @LterHaar!
> 
> 
> 
> A few tiny things (fine if @TiBiBa picks these up)
> 
> 
> 
> The overview looks goed, but it seems we lost syntax highlighting in the quiz? 
> 
> 
> 
> <img width="994" alt="image" src="https://user-images.githubusercontent.com/1003685/158546960-b23fe742-a06b-43db-bdb4-540f238d0d8e.png">
> 
> 
> 
> Also, probably very tiny but the overview (goed, pogingen) is in Duch even though my lang is English:
> 
> 
> 
> <img width="1052" alt="image" src="https://user-images.githubusercontent.com/1003685/158547045-1259d994-7578-4687-bfea-7f73a9e7ed87.png">
> 
> 
> 
> And if we are on the topic of languages anyway, this "Good" is a bit Dunglish, "correct" would be nicer:
> 
> 
> 
> <img width="482" alt="image" src="https://user-images.githubusercontent.com/1003685/158547185-d451a203-ed48-4c45-ae0a-4688e2e6d205.png">
> 
> 

Quiz syntax highlighting is not merged yet and an open PR #2208.

2022-03-16 10:51 UTC, Felienne commented
> Quiz syntax highlighting is not merged yet and an open PR #2208.

My bad, I approved it but did not merge yet, merged it now and all looks fine for this PR too.

2022-03-16 12:27 UTC, Felienne requested changes
This can be merged when we have cleared up the Dutch/English text issue (@TiBiBa, can you look into that?)

2022-03-18 13:52 UTC, TiBiBa commented
I have some issues with fixing the questions iterating. Will leave this a draft for now and fix this on Sunday!

2022-03-20 17:12 UTC, TiBiBa commented
@Felienne I think this one is good to go! I made some small fixes:

- Implemented language dependent strings
- Added syntax highlighting to results page
- Fix some small styling issues

2022-03-21 07:53 UTC, Felienne commented
> @Felienne I think this one is good to go! I made some small fixes:
> 
> * Implemented language dependent strings
> * Added syntax highlighting to results page
> * Fix some small styling issues

Great! I will try to have a look today but I am lecturing all day so maybe it'll be tomorrow

2022-03-21 10:33 UTC, Felienne commented on coursedata/texts/nl.yaml
>      correct: "Juist"
```suggestion
    correct: "Goed"
```

2022-03-21 10:33 UTC, Felienne commented on coursedata/texts/nl.yaml
>      correct: "Juist"
Vind ik toch wat Nederlandser

2022-03-21 10:34 UTC, Felienne commented on coursedata/texts/nl.yaml
>      incorrect: "Onjuist!"
```suggestion
    incorrect: "Niet goed!"
```

2022-03-21 10:34 UTC, Felienne approved these changes

2022-03-21 10:36 UTC, Felienne approved these changes
Helemaal in orde nu @LotusterHaar!

2022-03-21 10:42 UTC, merged