[BUGFIX] Allow spaces after square brackets and braces
Felienne/hedy pull request #2363
Opened 2022-03-30 02:06 UTC by jpelay

**Description**

As requested in #1772 I added the possibility to write spaces around square brackets and braces, just like you can in Python. So now is possible to write something like: `names [ 1 ]`  instead of throwing a parse exception.

Fixes #1772 

**How to test**

I added a test to show this behavior.
 
- [x ] Describes changes in the format above (present tense)
- [x] Links to an existing issue or discussion 
- [x] Has a "How to test" section

2022-03-30 07:18 UTC, Felienne commented
Great work, thanks @jpelay! Do we also want to do this for `<` and other comparisons?

2022-03-30 07:24 UTC, Felienne commented
That will also allow us to simplify, for example in level 14: `smaller: comparison_arg _SPACE? _SMALLER _SPACE? comparison_arg` -> `smaller: comparison_arg _SMALLER comparison_arg`

2022-03-30 07:38 UTC, Felienne requested changes
Setting this to request changes to a) keep an overview and b) make sure we con't close the issue while there is more improvement to be made

2022-04-02 11:31 UTC, Felienne commented
> > Setting this to request changes to a) keep an overview and b) make sure we con't close the issue while there is more improvement to be made
> 
> Hi @Felienne! I think that's an excellent idea, and it's already done. 

Thanks!!

> A more interesting case would be keywords, do we want to add _SPACE around keywords such as `is` or `in` which are 
> always surrounded by spaces? Maybe also for all of the others?
> 
> This would allow to simplify this `ask: var _SPACE _IS _SPACE _ASK (_SPACE _print_argument)?`
> 
> to this
> 
> `ask: var _IS _ASK (_SPACE _print_argument)?`
> 
> which already looks nice, or to this:
> 
> `ask: var _IS _ASK (_print_argument)?`

Yes, that is a great idea! Do you want to do that in this PR also or in a separate one?

2022-04-02 13:46 UTC, jpelay commented
> > > Setting this to request changes to a) keep an overview and b) make sure we con't close the issue while there is more improvement to be made
> > 
> > 
> > Hi @Felienne! I think that's an excellent idea, and it's already done.
> 
> Thanks!!
> 
> > A more interesting case would be keywords, do we want to add _SPACE around keywords such as `is` or `in` which are
> > always surrounded by spaces? Maybe also for all of the others?
> > This would allow to simplify this `ask: var _SPACE _IS _SPACE _ASK (_SPACE _print_argument)?`
> > to this
> > `ask: var _IS _ASK (_SPACE _print_argument)?`
> > which already looks nice, or to this:
> > `ask: var _IS _ASK (_print_argument)?`
> 
> Yes, that is a great idea! Do you want to do that in this PR also or in a separate one?

Thank you! Can I do it in a new one? Because I think that that will involve changing the translation structure a bit!

2022-04-02 13:59 UTC, Felienne commented
ok! I made an issue for you: https://github.com/Felienne/hedy/issues/2410

2022-04-02 14:00 UTC, Felienne commented
> Thank you! Can I do it in a new one? Because I think that that will involve changing the translation structure a bit!

ok! I made an issue for you: https://github.com/Felienne/hedy/issues/2410

2022-04-02 14:00 UTC, Felienne approved these changes

2022-04-02 14:00 UTC, Felienne commented on grammars/level14-Additions.lark
> +equality_check_dequals: comparison_arg  _DOUBLE_EQUALS  comparison_arg
Such a nice cleanup of the grammar!

2022-04-02 14:07 UTC, merged