fix quiz level 7
Felienne/hedy pull request #2379
Opened 2022-03-30 15:23 UTC by OnnoEbbens

Fixed some errors and translated some English to Dutch. Also replaced question 10 with a question from one of my students :)

2022-03-30 17:40 UTC, TiBiBa requested changes

2022-03-30 17:40 UTC, TiBiBa commented on coursedata/quizzes/nl.yaml
> +                "feedback": "Dit is een komma, je hebt een aanhalingstekens nodig."
Or of course `Dit is een komma, je hebt een aanhalingsteken nodig.`

2022-03-31 08:34 UTC, TiBiBa approved these changes

2022-04-01 09:37 UTC, Felienne approved these changes

2022-04-01 09:48 UTC, merged