[UI IMPROVEMENT] Implements ace editor on programs page
Felienne/hedy pull request #2499
Opened 2022-04-11 13:09 UTC by TiBiBa

**Description**
In this PR we implement the ace editor on the programs and clean-up the scripts there as well. For some reason the client side messages where not included on this page, creating a possible bug where no feedback would be returned to the user on an unexpected error. But most importantly, we now support syntax highlighting on the programs page.

**Fixes**
This PR fixes #2495.

**How to test**
Navigate to the `/programs` page and notice the new ace editors for each stored program. We limit the program shown to 4 lines, the rest is already discarded in the back-end.

2022-04-11 17:57 UTC, Felienne commented on app.py
> +            {'id': item['id'], 'code': "\n".join(item['code'].split("\n")[:4]), 'date': date, 'level': item['level'], 'name': item['name'],
This is a bit of stringy magic to me, not opposed to it but shall we add a comment to explain?

2022-04-11 17:58 UTC, Felienne requested changes
Add comment explaining the [:4]

2022-04-12 08:37 UTC, TiBiBa commented
Fixed!

2022-04-12 11:33 UTC, Felienne commented on app.py
> +        # We split the code on the newlines, take the last 4 and merge these with newlines again
```suggestion
```

2022-04-12 11:33 UTC, Felienne commented on app.py
> +        # We split the code on the newlines, take the last 4 and merge these with newlines again
Guess it is enough to just say we only want to show the 4st 4 lines

2022-04-12 11:36 UTC, Felienne approved these changes
Ah looks nice!

<img width="976" alt="image" src="https://user-images.githubusercontent.com/1003685/162951575-08255775-4ab3-4215-8d9a-11427f1f01c2.png">

2022-04-12 11:45 UTC, merged