Adds repeat keyword to levels 11+
Felienne/hedy pull request #2572
Opened 2022-04-21 02:17 UTC by huang-v

**Description**

Removes code that removes keyword "repeat" from valid commands in level 11 which enables repeat to be used for levels 11+

**Fixes _issue or discussion number_**

@1942

**How to test**

Repeat tests were added to level 11 as that is where the keyword is removed from the cumulative command variable and all levels were manually tested 

**Checklist**
  
- [x] Describes changes in the format above (present tense)
- [x] Links to an existing issue or discussion 
- [x] Has a "How to test" section

2022-04-22 09:40 UTC, Felienne commented on hedy.py
> -    11 :['ask', 'is', 'print', 'sleep', 'at', 'random', 'add', 'to', 'remove', 'from', 'in', 'if', 'else', 'for', 'range'],
It seems we are adding and not removing repeat here?

2022-04-22 09:42 UTC, Felienne requested changes
Hi @huang-v,

This PR seems to be a mix of adding and removing repeat? The title of the PR says adding but the text says removing, and the code seems to mix it too.

I know that the issue itself is also formulated very vaguely, so maybe this is our bad also!

Ultimately we want to have smooth level borders and allow repeat that way, so maybe we should just leave this all as it is now.

2022-04-22 11:04 UTC, huang-v commented
Sorry for the confusing wording.
I was told that "The idea was to add repeat to levels over 11."

The list of available keywords is based on the command variable in the lark files. Before, the repeat keyword was removed at level 11. I removed this removal however which essentially adds repeat to levels 11+

2022-04-25 11:20 UTC, Felienne commented
ok got it!

2022-04-25 14:15 UTC, merged