Request for work: the JS bundle is growing extremely large 😇
Felienne/hedy pull request #2672
Opened 2022-05-02 19:37 UTC by rix0rrr

Hi @thjazi39,

I know we agreed to make the syntax highlighter work this way, but I underestimated the sheer size of the data we would be generating this way. The JavaScript bundle is now 1.6MB in size, and that's too large to be acceptable...

I changed the script so it prints the reasons for the size:

```
  static/js/appbundle.js        1.6mb ⚠️
  static/js/appbundle.js.map  923.1kb

⚡ Done in 62ms

  static/js/appbundle.js                                                 1.6mb  100.0%
   ├ node_modules/chart.js/dist/chart.js                               188.3kb   11.5%
   ├ __tmp__/highlighting/highlightingRules/highlighting-hi.json        63.6kb    3.9%
   ├ __tmp__/highlighting/highlightingRules/highlighting-ar.json        61.3kb    3.8%
   ├ __tmp__/highlighting/highlightingRules/highlighting-zh_Hans.json   58.1kb    3.6%
   ├ __tmp__/highlighting/highlightingRules/highlighting-tr.json        56.8kb    3.5%
   ├ __tmp__/highlighting/highlightingRules/highlighting-de.json        56.2kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-pl.json        56.1kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-es.json        56.0kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-nl.json        56.0kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-fr.json        56.0kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-id.json        56.0kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-nb_NO.json     55.8kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-bg.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-bn.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-cs.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-el.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-en.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-fa.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-fy.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-hu.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-it.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-pt_BR.json     55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-pt_PT.json     55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-ru.json        55.6kb    3.4%
   ├ __tmp__/highlighting/highlightingRules/highlighting-sw.json        55.6kb    3.4%
   ├ __tmp__/static/js/app.js                                           27.5kb    1.7%
   ├ node_modules/dompurify/dist/purify.js                              19.8kb    1.2%
   ├ __tmp__/static/js/statistics.js                                    14.5kb    0.9%
   ├ __tmp__/static/js/teachers.js                                      10.2kb    0.6%
   ├ __tmp__/static/js/auth.js                                           7.9kb    0.5%
   ├ __tmp__/static/js/modal.js                                          4.5kb    0.3%
   ├ __tmp__/static/js/tabs.js                                           3.0kb    0.2%
   ├ __tmp__/static/js/syntaxModesRules.js                               1.9kb    0.1%
   ├ __tmp__/static/js/translating.js                                    1.3kb    0.1%
   └ __tmp__/static/js/index.js                                          480b     0.0%
```

And it turns out that the syntax highlighting rules are responsible for 24 * 55kB = 1.3MB of the bundle size now.

Here's a friendly request to do something clever to get that size down 😇. Maybe find an encoding of the rules that gets rid of the duplication?

2022-05-03 07:16 UTC, thjazi39 commented
I don't know if this is possible, but instead of preloading all the languages in the appbundle, maybe it would be possible to not preload anything, and only load the language used by the user, when the page is loaded?

2022-05-03 08:01 UTC, rix0rrr commented
> maybe it would be possible to not preload anything, and only load the language used by the user, when the page is loaded?

Maybe. Please investigate this. Keeping the following in mind while doing so:

- Loading files from the internet takes time. What will the user observe during that time?
- JavaScript is single-threaded, and the thread must not block, which means file loading will have to be asynchronous. What (if anything) does that change about the code structure?
- What if the user changes the language while the page is already loaded?
- What if the file does not exist?

2022-05-03 10:00 UTC, Felienne commented
> I don't know if this is possible, but instead of preloading all the languages in the appbundle, maybe it would be possible to not preload anything, and only load the language used by the user, when the page is loaded?

Sure we might be able to do something with smart loading, but the fact remains that there really is a lot of duplication in all the json files (basically, only the keywords differ and the rest is the same), which we could minimize to save traffic/space. Could you investigate how to do that?

2022-05-03 10:44 UTC, thjazi39 commented
Concretely, it would be like having a single JSON rule file, and rebuilding the translations in typescript?

This will require some changes, but it is possible.

Regarding the testing of the translations, it will mean that we will have to mimic this process of translations, but since this is not a part that will move a lot, it should not be a problem!

2022-05-03 11:07 UTC, Felienne commented
> Concretely, it would be like having a single JSON rule file, and rebuilding the translations in typescript?

Yes that was the idea, that saves a lot of files.

> This will require some changes, but it is possible.

Great! And then indeed we can try to do it as you proposed, only for the language that the user has selected to save processing power.

> Regarding the testing of the translations, it will mean that we will have to mimic this process of translations, but since this is not a part that will move a lot, it should not be a problem!

Great!!

2022-05-05 19:57 UTC, thjazi39 commented
The translation of regexes is now operational, I hope it does not break anything in the front-end

2022-05-05 19:59 UTC, thjazi39 approved these changes

2022-05-06 09:38 UTC, TiBiBa requested changes
It doesn't seem to work as expected everywhere for me. When on English, level 1 works fine but level 2 and 3 only support partly syntax highlighting. I tried compiling the TypeScript again but this doesn't make any difference. See the screenshot below for clarification:

![Schermafbeelding 2022-05-06 om 11 36 12](https://user-images.githubusercontent.com/38155424/167107060-ad84d71d-7760-4280-8cca-102ef9463316.png)
![Uploading Schermafbeelding 2022-05-06 om 11.36.17.png…]()

2022-05-06 09:38 UTC, TiBiBa commented on build-tools/heroku/generate-typescript
> +        --analyze \
Would be nice if we remove this parameter when deploying.

2022-05-06 16:58 UTC, TiBiBa approved these changes
Looks good!

2022-05-06 21:29 UTC, merged