[UI IMPROVEMENT] Improve cheatsheet UI
Felienne/hedy pull request #2906
Opened 2022-06-16 08:25 UTC by TiBiBa

**Description**
In this PR we improve the UI of the cheatsheets, making a better differentiation between the different commands.

**Fixes**
No related issue (partly discusses and fixes #2904).

**How to test**
Navigate too `/cheatsheet/<level>` and verify that the generated cheatsheet looks as expected and works.

**New view**
![Schermafbeelding 2022-06-16 om 10 19 31](https://user-images.githubusercontent.com/38155424/174026965-ac6d0ca2-ffd8-40fb-9d6b-bfeb451036e5.png)

2022-06-16 20:44 UTC, Felienne requested changes
While checking the Arabic demo I found out that the Ace is not r2l in the cheat sheets:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1003685/174160313-8a3c8752-aec5-4484-a888-8dee59357fe1.png">

Whoopsie :) 

Not caused by this PR but would be nice to fix.

2022-06-21 07:19 UTC, TiBiBa commented
> While checking the Arabic demo I found out that the Ace is not r2l in the cheat sheets:
> 
> <img alt="image" width="1040" src="https://user-images.githubusercontent.com/1003685/174160313-8a3c8752-aec5-4484-a888-8dee59357fe1.png">
> 
> Whoopsie :)
> 
> Not caused by this PR but would be nice to fix.

Weird, this should automatically be caught; will look into this!

2022-06-21 07:26 UTC, TiBiBa commented
Fixed!
![Schermafbeelding 2022-06-21 om 09 25 21](https://user-images.githubusercontent.com/38155424/174741060-501d7083-c051-4352-aeb6-cdc97f0079a1.png)

2022-06-21 19:21 UTC, Felienne commented on static/js/app.ts
> +  const dir = $("body").attr("dir");
Just because I am curious... why does this fix rtl? Does body have a certain setting so that it works?

2022-06-21 19:21 UTC, Felienne approved these changes

2022-06-22 11:16 UTC, merged