Quiz attempts
Felienne/hedy pull request #622
Opened 2021-08-10 11:39 UTC by Fl0werth

The student has got 3 attempts to answer a question. The score is diminished for every attempt ( 100% - 50% - 25 % - 0%). 
Layout is adjusted to the new functionality of multiple attempts.

2021-08-16 08:56 UTC, fpereiro commented
Hi @LotusterHaar ! It's looking good. Just tested it locally and it works well. Apart from the comment above about setting the quiz attempts as a variable (also reaching the template as well), we should be good to go :)

2021-08-16 08:57 UTC, fpereiro commented
@LotusterHaar before merging you should merge `main` onto the branch and regenerate the Tailwind CSS so we can avoid the merge conflict on that file.

2021-08-16 12:49 UTC, Felienne commented
Ziet er goed uit @Fl0werth! Twee kleine dingen vanuit mijn kant:

* Ik zat te denken over de tekst van "Doe poging 1 voor vraag X" enz, wat denk je van "Beantwoord vraag X"? De pogingen hoeven niet perse in de knop van mij, die staan er al duidelijk boven, en dan is de knop ook wat compacter.

* En op mijn scherm moet je nu scrollen voor de knop naar de volgde pagina, de knop valt er net af:

![image](https://user-images.githubusercontent.com/1003685/129566280-6159e0b5-8432-4329-a8d1-8937f984dae7.png)

Zouden we die iets omhoog kunnen zetten?

2021-08-16 13:30 UTC, fpereiro approved these changes
Great work!

2021-08-17 18:01 UTC, Felienne requested changes

2021-08-17 18:01 UTC, Felienne commented on templates/quiz_question.html
> +                {% if attempt == 3 %}
Deze tekst dus liever even aanpassen (zie comment op de PR zelf)

2021-09-07 13:23 UTC, Felienne commented
@Fl0werth There are some merge conflicts now on this PR, could you resolve those?

2021-09-15 08:17 UTC, merged