Classes overview in Teachers Page
Felienne/hedy pull request #694
Opened 2021-08-29 21:01 UTC by fpereiro

- Move classes overview to For Teachers page.
- Hide For Teachers page from main menu unless the user is a teacher.
- Related to (but doesn't close) #546 

This PR is missing the logic for showing different parts of the teachers doc in an expandable/shrinkable way. The two features listed above, however, should be fully working.

An implementation note: we retrieve the classes through AJAX, which makes the population of the classes on the table happen 1-2 seconds after the initial drawing of the page. It perhaps would make sense to remove loading the classes from AJAX and do it directly on the template (the whole page would take more time to load, but it would be drawn at once). This would entail isolating the logic for loading classes onto its own function, which can then be called from a couple of places.

@Felienne I submitted the PR since we might want to test/merge this ASAP (since the semester starts now) and leave the expandable/shrinkable docs for the very near future.

2021-08-30 06:31 UTC, Felienne commented
Clicking a class gives an error (maybe because it is empty?) 

 ![image](https://user-images.githubusercontent.com/1003685/131295210-a489de11-17e0-4756-ac6c-ee6f62e0cae3.png)

That means I cannot test the rest of the flow cause I can't invite new kids into the class

2021-08-30 06:33 UTC, Felienne commented
Unified modal (nice that we now use that everywhere!) is empty for Dutch:

![image](https://user-images.githubusercontent.com/1003685/131295599-bdafdb00-6aae-4b8a-bff3-a7ebdd6a55d6.png)

2021-08-30 06:44 UTC, Felienne commented
Hi @fpereiro I tried the normal flow (make class, follow join lonk from a different account) but I run into several new and weird issues: stopping pages, logging out all of a sudden and more weird thing. Hard to pinpoint this but I guess a first step is you do a few more run throughs to see if it is all in order for you.

2021-08-30 10:05 UTC, Felienne commented
While I am trying to figure out all the weird issues (not yet succeeded in that), there are some cosmetic ones too. "Ja" is a bit weird here, "ok" would be better:

![image](https://user-images.githubusercontent.com/1003685/131323128-73490931-f22a-4cc0-bd06-e0ad5c4e46dd.png)

2021-09-06 12:43 UTC, fpereiro commented on build-tools/validate-e2e
> +env HEROKU_APP_NAME=localhost BASE_URL=http://localhost:$PORT SECRET_KEY=TheSecret python app.py > e2e-server.log 2>&1 &
Hi @rix0rrr ! I just added the `BASE_URL` env variable to the script that runs the E2E tests. We need that variable now on a couple places other than the email sending. Let me know if this looks right to you as well.

2021-09-07 18:11 UTC, Felienne requested changes
Hi @fpereiro I just tested it again and it seems to be fine now!

I have two tiny remarks:
* Can we place a note in profile (just a line at the top), for logged in teachers, telling them the class overview is moved?
* If a kid tries to join a class they are already in, can we give them a warning? Rather than rendering the page and making hem click again, can we give them the warning when they clink the first link (only when that is easy to make, don't spend lots of time on it!)

2021-09-07 18:11 UTC, Felienne commented on templates/profile.html
> -  <div id="teacher_classes" class="hidden pl-8">
This is fixed!

2021-09-09 08:55 UTC, fpereiro commented
Summary of missing work:
- Add a list of shared programs for each student in a column.
- Add a note that tells teachers that Class Overview moved.
- Change text into actual link (closes #685)
- Add rename class button
- When joining a class a user already joined, tell them that they have already joined the class.

2021-09-09 13:56 UTC, fpereiro commented
@Felienne ready for review again!

2021-09-09 14:43 UTC, merged