fix: load_yaml_pickle test fails if a pickled file is on disk
Felienne/hedy pull request #734
Opened 2021-09-10 17:35 UTC by rix0rrr

The pickle test that loads `hu.yaml` compares it to loading
`hu.yaml.pickle`; if there was a `.pickle` file remaining on
disk, it may have different contents than the `.yaml` file.

This will not happen on the server since it gets a clean redeploy
every time, but it may happen on dev machines.

2021-09-11 11:31 UTC, fpereiro commented
@rix0rrr thank you for the fix!

2021-09-11 13:19 UTC, Felienne commented
> @rix0rrr thank you for the fix!

Beware, this fix is not ready yet! @rix0rrr needs to dive into the issue a bit deeper.

2021-09-11 13:21 UTC, Felienne requested changes
This is now in the exact state that is was for me too (locally) with the weird numeric postfix on the filename, no clue why that happens!

2021-09-13 18:21 UTC, Felienne approved these changes

2021-09-13 18:31 UTC, merged