Allow empty programs in the grammar
Felienne/hedy pull request #849
Opened 2021-10-02 12:29 UTC by bjorn3

The empty program check is now moved to IsValid and will handle programs consisting entirely of newlines without crashing.

Programs consisting entirely of spaces do still give a parse error, but unlike newline only programs previously they don't crash Hedy.

Fixes https://github.com/Felienne/hedy/issues/833

2021-10-03 08:25 UTC, Felienne commented
btw, I just realized we had an issue open for this: #668

2021-10-03 10:38 UTC, Felienne requested changes

2021-10-04 16:39 UTC, bjorn3 commented on coursedata/texts/en.yaml
> +    Empty Program: No code found, please enter some code.
Added translation. I will use branches on this repo in the future.

2021-10-04 16:49 UTC, Felienne commented on coursedata/texts/en.yaml
> +    Empty Program: No code found, please enter some code.
Thanks, awesome! on merge this goes to hedy-alpha.herokuapp.com so if you want to you can see if all works well there.

2021-10-04 16:49 UTC, Felienne commented on coursedata/texts/en.yaml
> +    Empty Program: No code found, please enter some code.
Thanks, awesome! on merge this goes to hedy-alpha.herokuapp.com so if you want to you can see if all works well there.

2021-10-04 16:50 UTC, Felienne approved these changes

2021-10-04 16:50 UTC, Felienne commented on coursedata/texts/nl.yaml
> +    Empty Program: "Er was geen code gevonden. Typ graag wat code in."
Wat een grappige formulering, je zou bijna denken dat het uit Translate komt. Ik fix zo wel even in ietsje indiomatischer.

2021-10-04 16:50 UTC, merged